language: perl
sudo: false

install:
  - perlbrew list
  - (dzil authordeps --missing | cpanm -n) || true
  - dzil listdeps   --missing | cpanm -n
  - perl corpus/server.pl

perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"

script:
  - dzil test -v

env:
  - ALIEN_BUILDER_LIVE_TEST=4701:4702
